### ISSUE TITLE
typo, connection should be con

### ISSUE THREAD

**Issue by orenshk** [dwavesystems/dwave_micro_client#8]
https://github.com/dwavesystems/dwave_micro_client/blob/fd86de8a2a5968dab6ce0a70b771526335255494/dwave_micro_client.py#L24

**Comment by ccoffrin** [comment]
On a related note, some examples on this page use `con` and others `conn`.

http://dwave-micro-client.readthedocs.io/en/latest/

**Comment by randomir** [comment]
I believe this is now fixed with #23.
